name: Demo Flask app CI

on:
  push:
    branches:
      - main

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build -t flask-demo-app .

      - name: Show Docker image
        run: |
          docker images

      - name: Run Docker container
        run: |
          docker run -d -p 5000:5000 --name flask-demo-app flask-demo-app 

      - name: Waiting to run the app
        run: |
          sleep 10
         
      - name: checking the app running
        run: |
          curl http://localhost:5000

      - name: Checking container logs
        run: |
          docker logs flask-demo-app    

  docker-push:
    runs-on: ubuntu-latest
    needs: docker-build
      
    steps:
      
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/flask-demo-app:${{ github.sha }} .
          
      - name: Check Docker Image    
        run: |
          docker image

      - name: Login in Docker Hub
        uses: docker/login-action@v3
        with: 
          username: ${{ secrets.DOCKER_USERNAME }} 
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/flask-demo-app:${{ github.sha }}      

        
          
