name: flask demo CI
  on:
    push:
      branches:
        - main

jobs:
  docker-buils:
    run-on: ubuntu-latest
      
    steps:

      - name: checkout code
        uses: actions/checkout@v4

      - name: docker build
        run: |
          docker build -t flask-demo .

      - name: Run docker container
        run: |
          docker run -d -p 5000:5000 --name flask-demo flask-demo

      - name: show running container
        run: |
          docker ps    
           



